Web_DS/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""
URL configuration for Web_DS project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('uploads/', include('uploads.urls')),
    path('classifier/', include('classifier.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classifier/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'classifier'
urlpatterns = [
    path('model/<int:dataset_id>/', views.model, name='model'),
    path('predict/<int:dataset_id>/', views.predict, name='predict'),
    path('result/<int:dataset_id>/', views.result, name='result'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('panduan/', views.panduan, name='panduan'),
    path('prediksi/', views.prediksi, name='prediksi'),
    path('contact/', views.contact, name='contact'),
    path('daftar_dataset/', views.list_dataset, name='list_dataset'),
]

uploads/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'uploads'
urlpatterns = [
    path('', views.index, name='index'),
    path('custom/<int:dataset_id>/', views.custom, name='custom'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from uploads.models import Dataset
# Create your views here.

def index(request):
    context = {}
    dataset = Dataset.objects.all()
    context['datasets'] = dataset
    return render(request, 'home/index.html', context)

def about(request):
    return render(request, 'about/about.html')

def panduan(request):
    return render(request, 'panduan/panduan.html')

def prediksi(request):
    return render(request, 'prediksi/prediksi.html')

def contact(request):
    return render(request, 'contact/contact.html')

def list_dataset(request):
    context = {}
    dataset = Dataset.objects.all()
    context['datasets'] = dataset
    return render(request, 'home/listDataset.html', context)

home/templates/home/index.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
    Heart Predict | Home
{% endblock %}
{% block index %}
    current-list-item
{% endblock %}
{% block content %}
    <!-- hero area -->
    <div class="hero-area hero-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 offset-lg-2 text-center">
            <div class="hero-text">
              <div class="hero-text-tablecell">
                <p class="subtitle">Your health is important</p>
                <h1>Prediksi Gagal Jantung</h1>
                <div class="hero-btns">
                  <a href="{% url 'home:list_dataset' %}" class="boxed-btn">Cek Sekarang</a>
                  <a href="{% url 'home:panduan' %}" class="bordered-btn">Cara Kerja</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end hero area -->

    <!-- features list section -->
    <div class="list-section pt-80 pb-80">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
            <div class="list-box d-flex align-items-center">
              <div class="list-icon">
                <i class="fas fa-user-md"></i>
              </div>
              <div class="content">
                <h3>Prediksi Risiko</h3>
                <p>dengan Akurasi Tinggi</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
            <div class="list-box d-flex align-items-center">
              <div class="list-icon">
                <i class="fas fa-phone-volume"></i>
              </div>
              <div class="content">
                <h3>Layanan Gratis</h3>
                <p>dan Mudah Digunakan</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div
              class="list-box d-flex justify-content-start align-items-center">
              <div class="list-icon">
                <i class="fas fa-random"></i>
              </div>
              <div class="content">
                <h3>Dengan Algoritma</h3>
                <p>Decision Tree</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end features list section -->

    <!-- testimonail-section -->
    <div class="testimonail-section mt-150 mb-150">
      <div class="container">
        <div class="row">
          <div class="col-lg-10 offset-lg-1 text-center">
            <div class="testimonial-sliders">
              <div class="single-testimonial-slider">
                <div class="client-avater">
                  <img src="assets/img/avaters/avatar1.png" alt="" />
                </div>
                <div class="client-meta">
                  <h3>
                    dr. Isman Firdaus Sp.JP (K), FIHA, FAPSIC, FAsCC, FESC,
                    FSCAI <span>p2ptm.kemkes.go.id</span>
                  </h3>
                  <p class="testimonial-body">
                    " Gagal jantung adalah kondisi yang serius dan bisa
                    mengancam nyawa. Jika tidak diobati dengan tepat, dapat
                    menyebabkan komplikasi fatal. "
                  </p>
                  <div class="last-icon">
                    <i class="fas fa-quote-right"></i>
                  </div>
                </div>
              </div>
              <div class="single-testimonial-slider">
                <div class="client-avater">
                  <img src="assets/img/avaters/avatar2.png" alt="" />
                </div>
                <div class="client-meta">
                  <h3>
                    dr. Facmi Achmad m, Sp.Jp.FIHA
                    <span>primayahospital.com</span>
                  </h3>
                  <p class="testimonial-body">
                    " Gagal jantung kongestif merupakan silent killer yang
                    berbahaya. Masyarakat perlu mengenali gejalanya dan mencari
                    perawatan secepat mungkin. "
                  </p>
                  <div class="last-icon">
                    <i class="fas fa-quote-right"></i>
                  </div>
                </div>
              </div>
              <div class="single-testimonial-slider">
                <div class="client-avater">
                  <img src="assets/img/avaters/avatar3.png" alt="" />
                </div>
                <div class="client-meta">
                  <h3>dr. Pittara <span>alodokter.com</span></h3>
                  <p class="testimonial-body">
                    " Berbagai spektrum penyakit kardiovaskular, termasuk gagal
                    jantung, dapat menjadi ancaman serius bagi kesehatan
                    jantung. "
                  </p>
                  <div class="last-icon">
                    <i class="fas fa-quote-right"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end testimonail-section -->

    <!-- advertisement section -->
    <div class="abt-section mb-150">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <div class="abt-bg">
              <a
                href="https://www.youtube.com/watch?v=y6w8EehiDek"
                class="video-play-btn popup-youtube"
                ><i class="fas fa-play"></i
              ></a>
            </div>
          </div>
          <div class="col-lg-6 col-md-12">
            <div class="abt-text">
              <p class="top-sub">www.heartpredict.com</p>
              <h2>Kenapa <span class="orange-text">HeartPredict</span></h2>
              <p>
                Berdasarkan hasil penelitian yang dipublikasikan pada
                International Journal of Cardiology, jumlah penderita gagal
                jantung di Indonesia adalah sebesar 5% dari total jumlah
                penduduk. Deteksi dini dan pencegahan adalah kunci untuk
                mengurangi jumlah kematian akibat penyakit jantung.
              </p>
              <p>
                Dalam upaya mitigasi penyakit jantung, perkembangan teknologi
                telah memberikan alat yang dapat membantu dalam diagnosis dini
                penyakit jantung. Dengan demikian, web prediksi ini dapat
                menjadi alat yang sangat berguna untuk membantu dalam deteksi
                dini, pencegahan, dan pengelolaan penyakit jantung.
              </p>
              <a href="{% url 'home:about' %}" class="boxed-btn mt-4">Selengkapnya</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end advertisement section -->

    <!-- shop banner -->
    <section class="shop-banner">
      <div class="container">
        <h3>
          Periksa Sekarang! <br />
          sebelum <span class="orange-text">Terlambat</span>
        </h3>
        <div class="sale-percent">
          <span>Hanya di www.</span>HeartPredict<span>.com</span>
        </div>
        <a href="{% url 'home:list_dataset' %}" class="cart-btn btn-lg">Mulai</a>
      </div>
    </section>
    <!-- end shop banner -->
{% endblock %}

home/templates/home/listDataset.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
    Heart Predict | Daftar Dataset
{% endblock %}
{% block prediksi %}
    current-list-item
{% endblock %}
{% block content %}

    <!-- breadcrumb-section -->
    <div class="breadcrumb-section breadcrumb-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 offset-lg-2 text-center">
            <div class="breadcrumb-text">
              <p>Coba Sekarang</p>
              <h1>Prediksi</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end breadcrumb section -->
    <!-- Daftar Dataset Start -->
    <div class="single-product mt-150 mb-150">
      <div class="container">
        <div class="row">
          <!-- <div class="col-md-1">
					<img src="{% static 'img/number/1.png' %}" alt="">
				</div> -->
          <div class="col-md-11">
            <div class="single-product-content">
                <h2>Daftar Dataset</h2>
                <p>
                    Berikut adalah daftar dataset yang tersedia di website ini.
                </p>
                <div class="table-responsive">
                    <table class="table table-bordered">
                    <thead>
                        <tr>
                        <th scope="col">No</th>
                        <th scope="col">Nama Dataset</th>
                        <th scope="col">Link Dataset</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dataset in datasets %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ dataset.title }}</td>
                            <td><a href="{% url 'classifier:model' dataset_id=dataset.id %}">tekan link ini</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Daftar Dataset End -->
    
    <!-- Upload Dataset Start -->
    <div class="single-product mt-150 mb-150">
      <div class="container">
        <div class="row">
          <!-- <div class="col-md-1">
					<img src="{% static 'img/number/1.png' %}" alt="">
				</div> -->
          <div class="col-md-11">
            <div class="single-product-content">
                <p> Ingin upload Dataset Baru ?</p>
                <p>Silahkan Tekan tombol Dibawah ini</p>
                <a href="{% url 'uploads:index' %}" class="btn" style="background-color: #D75E72; color: #fff; padding: 10px 15px;">Upload Dataset</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Upload Dataset End -->

    
{% endblock %}