Web_DS/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""
URL configuration for Web_DS project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('uploads/', include('uploads.urls')),
    path('classifier/', include('classifier.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('panduan/', views.panduan, name='panduan'),
    path('prediksi/', views.prediksi, name='prediksi'),
    path('contact/', views.contact, name='contact'),
    path('daftar_dataset/', views.list_dataset, name='list_dataset'),
]

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/" />

    <!-- title -->
    <title>{% block title %}Heart Predict{% endblock %}</title>

    <!-- favicon -->
    <link rel="icon" href="{% static 'img/favicon.png' %}" />
    <!-- google font -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"
      rel="stylesheet" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap"
      rel="stylesheet" />
    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <!-- bootstrap -->
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
    <!-- magnific popup -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <!-- mean menu css -->
    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}" />
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
  </head>
  <body>
    <!--PreLoader-->
    <div class="loader">
      <div class="loader-inner">
        <div class="circle"></div>
      </div>
    </div>
    <!--PreLoader Ends-->

    <!-- header -->
    <div class="top-header-area" id="sticker">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 text-center">
            <div class="main-menu-wrap">
              <!-- logo -->
              <div class="site-logo">
                <a href="index.html">
                  <img src="{% static 'img/logo.png' %%}" alt="" />
                </a>
              </div>
              <!-- logo -->

              <!-- menu start -->
              <nav class="main-menu">
                <ul>
                  <li class="{% block index %}  {% endblock %}">
                    <a href="{% url 'home:index' %}">Home</a>
                  </li>
                  <li class="{% block about %}  {% endblock %}">
                    <a href="{% url 'home:about' %}">About</a>
                </li>
                  <li class="{% block panduan %}  {% endblock %}">
                    <a href="{% url 'home:panduan' %}">Panduan</a>
                </li>
                  <li class="{% block prediksi %}  {% endblock %}">
                    <a href="{% url 'home:list_dataset' %}">Prediksi</a>
                </li>
                  <li class="{% block contact %}  {% endblock %}">
                    <a href="{% url 'home:contact' %}">Contact</a>
                </li>
                </ul>
              </nav>
              <div class="mobile-menu"></div>
              <!-- menu end -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end header -->

    <!-- content -->
        {% block content %}
        <!-- Konten utama akan ditempatkan di sini -->
        {% endblock %}
    <!-- content -->


    <!-- footer -->
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6">
            <div class="footer-box about-widget">
              <h2 class="widget-title">About us</h2>
              <p>
                Dalam upaya mitigasi penyakit jantung, perkembangan teknologi
                telah memberikan alat yang dapat membantu dalam diagnosis dini
                penyakit jantung. Dengan demikian, web prediksi ini dapat
                menjadi alat yang sangat berguna untuk membantu dalam deteksi
                dini, pencegahan, dan pengelolaan penyakit jantung.
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-box get-in-touch">
              <h2 class="widget-title">Get in Touch</h2>
              <ul>
                <li>Universitas Negeri Malang, Malang</li>
                <li><a href="https://um.ac.id/">www.um.ac.id</a></li>
                <li>(0341) 551312</li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-box pages">
              <h2 class="widget-title">Pages</h2>
              <ul>
                <li><a href="{% url 'home:index' %}">Home</a></li>
                <li><a href="{% url 'home:about' %}">About</a></li>
                <li><a href="{% url 'home:panduan' %}">Panduan</a></li>
                <li><a href="{% url 'home:list_dataset' %}">Prediksi</a></li>
                <li><a href="{% url 'home:contact' %}">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end footer -->

    <!-- copyright -->
    <div class="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <p>
              Copyrights &copy; 2024 -
              <a>Kelompok 3 Data Science | S1 TI A 2022</a>
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- end copyright -->

    <!-- jquery -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <!-- bootstrap -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- count down -->
    <script src="{% static 'js/jquery.countdown.js' %}"></script>
    <!-- isotope -->
    <script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
    <!-- waypoints -->
    <script src="{% static 'js/waypoints.js' %}"></script>
    <!-- owl carousel -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- magnific popup -->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <!-- mean menu -->
    <script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
    <!-- sticker js -->
    <script src="{% static 'js/sticker.js' %}"></script>
    <!-- main js -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>